version: '3.8' # Specify a modern compose version

services:
  teamcity-server:
    image: jetbrains/teamcity-server:2023.05.1
    ports:
      - "8111:8111"
    volumes:
      - teamcity-data:/data/teamcity_server/datadir
      - teamcity-logs:/opt/teamcity/logs
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx2g
      - TEAMCITY_SERVER_MEM_OPTS=-XX:ReservedCodeCacheSize=350m
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8111/healthCheck/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s 

  teamcity-agent:
    build: 
      context: .
      dockerfile: agent.Dockerfile
    container_name: custom-teamcity-agent 
    volumes:
      - teamcity-agent-conf:/data/teamcity_agent/conf
      - /home/roman/ansible:/ansible


    environment:
      - SERVER_URL=http://teamcity-server:8111
    restart: always
    depends_on:
      teamcity-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "ps aux | grep -v grep | grep -q 'TeamCity/buildAgent/bin' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  teamcity-data:
  teamcity-logs:
  teamcity-agent-conf:
